export const queryKeys = {
  setup: ["setup"] as const,
  setupDatabase: ["setup", "database"] as const,
  me: ["me"] as const,
  userSettings: ["user-settings"] as const,
  libraryOrder: ["library-order"] as const,
  home: ["home"] as const,
  favorites: ["favorites"] as const,
  libraries: ["libraries"] as const,
  library: (
    libraryId: string,
    page: number,
    itemTypes?: string,
    sortBy = "Name",
    sortOrder = "Ascending",
    metadataStatus = "all",
  ) => ["library", libraryId, page, itemTypes ?? "root", sortBy, sortOrder, metadataStatus] as const,
  item: (itemId: string) => ["item", itemId] as const,
  person: (personId: string) => ["person", personId] as const,
  personItems: (personId: string) => ["person", personId, "items"] as const,
  itemImages: (itemId: string) => ["item-images", itemId] as const,
  children: (itemId: string, itemType?: string, seasonId?: string) =>
    ["children", itemId, itemType ?? "default", seasonId ?? "all"] as const,
  playback: (itemId: string) => ["playback", itemId] as const,
  playbackBootstrap: (itemId: string, sourceId?: string | null, attempt = 0) =>
    ["playback-bootstrap", itemId, sourceId ?? "default", attempt] as const,
  webPlaybackSession: (itemId: string, sourceId: string, attempt: number) =>
    ["web-playback-session", itemId, sourceId, attempt] as const,
  adminDashboard: ["admin", "dashboard"] as const,
  adminHealth: ["admin", "health"] as const,
  adminLibraries: ["admin", "libraries"] as const,
  adminChapterSources: ["admin", "chapter-sources"] as const,
  adminPlugins: ["admin", "plugins"] as const,
  adminPluginStore: ["admin", "plugin-store"] as const,
  adminInstalledPlugins: ["admin", "plugins", "installed"] as const,
  adminNotificationProviders: ["admin", "notification-providers"] as const,
  adminWebhookDestinations: ["admin", "webhook-destinations"] as const,
  adminWebhookDeliveries: ["admin", "webhook-deliveries"] as const,
  adminUsers: ["admin", "users"] as const,
  adminJobs: (status?: string) => ["admin", "jobs", status ?? "all"] as const,
  adminTaskActivity: ["admin", "task-activity"] as const,
  adminScheduledTasks: (page = 1) => ["admin", "scheduled-tasks", page] as const,
  adminScheduledTaskPlans: (page = 1, taskType = "", search = "") =>
    ["admin", "scheduled-task-plans", page, taskType, search] as const,
  adminMetadataJobs: (status?: string) => ["admin", "metadata-jobs", status ?? "all"] as const,
  adminStrmProbeJobs: (status?: string) => ["admin", "strm-probe-jobs", status ?? "all"] as const,
  adminChapterDetectionJobs: (status?: string) => ["admin", "chapter-detection-jobs", status ?? "all"] as const,
  adminDanmakuMatchJobs: (status?: string) => ["admin", "danmaku-match-jobs", status ?? "all"] as const,
  adminLibraryCoverJobs: (status?: string) => ["admin", "library-cover-jobs", status ?? "all"] as const,
  adminLogs: ["admin", "logs"] as const,
  adminSettings: ["admin", "settings"] as const,
  adminApiKey: ["admin", "api-key"] as const,
  adminEmbyMigrations: (page = 1) => ["admin", "emby-migrations", page] as const,
  adminEmbyMigrationSourceUsers: (page = 1, search = "") => ["admin", "emby-migration", "source-users", page, search] as const,
  adminEmbyMigration: (jobId: string) => ["admin", "emby-migration", jobId] as const,
  adminEmbyMigrationUsers: (jobId: string, page = 1) => ["admin", "emby-migration", jobId, "users", page] as const,
  adminEmbyMigrationMatches: (jobId: string, page = 1) => ["admin", "emby-migration", jobId, "matches", page] as const,
  adminEmbyMigrationImports: (jobId: string, page = 1) => ["admin", "emby-migration", jobId, "imports", page] as const,
  adminEmbyMigrationPersonFavorites: (jobId: string, page = 1) => ["admin", "emby-migration", jobId, "person-favorites", page] as const,
  adminItemImages: (itemId: string) => ["admin", "item-images", itemId] as const,
};

export const queryRefreshIntervals = {
  liveDashboard: 15_000,
  mediaSurface: 15_000,
} as const;
